### ISSUE TITLE
Cannot compile on ubuntu 22.04

### ISSUE THREAD

**Issue by PocketPi** [DediProgSW/SF100Linux#50]
I cannot compile the tool on ubuntu 22.04

when i try to compile i get an error that libusb.h cannot be found: 

peter:/media/peter/data/code/SF100Linux(master)$ make 
make: pkg-config: No such file or directory
  CC  dpcmd.o
In file included from dpcmd.c:7:
usbdriver.h:6:10: fatal error: libusb.h: No such file or directory
    6 | #include <libusb.h>
      |          ^~~~~~~~~~
compilation terminated.
make: *** [Makefile:44: dpcmd.o] Error 1
peter:/media/peter/data/code/SF100Linux(master)$ 
peter:/media/peter/data/code/SF100Linux(master)$ 
peter:/media/peter/data/code/SF100Linux(master)$ git log
commit f5646a6fa966f2c2d0e3d7b2d234454fb9d4229a (HEAD -> master, origin/master, origin/HEAD)
Author: Evy liu <evy.liu@dediprog.com>
Date:   Tue Feb 15 10:28:54 2022 +0800

    Update usbdriver.c

I have installed libusb:

libusb-0.1-4/jammy,now 2:0.1.12-32build3 amd64 [installed]
libusb-1.0-0-dev/jammy,now 2:1.0.25-1ubuntu1 amd64 [installed]
libusb-1.0-0/jammy,now 2:1.0.25-1ubuntu1 amd64 [installed]
libusb-1.0-doc/jammy,jammy,now 2:1.0.25-1ubuntu1 all [installed]
libusb-dev/jammy,now 2:0.1.12-32build3 amd64 [installed]

**Comment by jacobmgn** [comment]
Modify the header file to include the folder

```
diff --git a/usbdriver.h b/usbdriver.h
index 72e00ff..e5862d4 100755
--- a/usbdriver.h
+++ b/usbdriver.h
@@ -3,7 +3,7 @@
 #ifndef DEDI_USB_DRIVER
 #define DEDI_USB_DRIVER

-#include <libusb.h>
+#include <libusb-1.0/libusb.h>
 #include <stdbool.h>
 #include <stdio.h>
 #include <string.h>
```

Your libusb is likely in `/usr/local/include`, but inside of a sub-folder.

On my Mac, where libusb was installed via brew, it was installed into a subfolder.

```
ls -l /usr/local/include/
total 0
lrwxr-xr-x  1 jacobmgn  admin   42 May 11 18:24 libusb-1.0 -> ../Cellar/libusb/1.0.26/include/libusb-1.0
lrwxr-xr-x  1 jacobmgn  admin   45 May 11 18:28 usb.h -> ../Cellar/libusb-compat/0.1.5_1/include/usb.h
```

**Comment by PocketPi** [comment]
it works 

can it get merged?

**Comment by DediprogEvy** [comment]
Hi,

I've modified the header file. 
Thanks.

DediProg Evy.

**Comment by jacobmgn** [comment]
Committed here https://github.com/DediProgSW/SF100Linux/commit/c76e10f03ab758b1dce1c54e586a7a14fbcf298a
